# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'A dream of reason'
tagline:             'discussions about this, that, and the other'
description:         'My personal blog, wherein I discuss programming, disability, literature, and everything in between.'
url:                 http://tranovich.io
baseurl:             /
paginate:            5

currently_reading:   "Francis Fukuyama's Political Order and Political Decay"

# About/contact
author:
  name:              James Tranovich
  email:             jtranovich@gmail.com
