# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'A dream of reason'
tagline:             'discussions about this, that, and the other'
description:         'My personal blog, wherein I discuss programming, disability, literature, and everything in between.'
url:                 http://tranovich.io
baseurl:             /
paginate:            5
excerpt_separator:   <!--more-->

currently_reading:
  - { name: "The Last Lion: Winston Spencer Churchill",
      review_link: "http://www.nytimes.com/2012/12/23/books/review/the-last-lion-by-william-manchester-and-paul-reid.html" }
  - { name: "Political Order and Political Decay",
      review_link: "http://www.washingtonpost.com/opinions/book-review-political-order-and-political-decay-by-francis-fukuyama/2014/10/24/57414b58-4e35-11e4-aa5e-7153e466a02d_story.html"}

# About/contact
author:
  name:              James Tranovich
  email:             jtranovich@gmail.com
