# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'A dream of reason'
tagline:             'discussions about this, that, and the other'
description:         'My personal blog, wherein I discuss programming, disability, literature, and everything in between.'
url:                 http://tranovich.io
baseurl:             /
paginate:            5
excerpt_separator:   <!--more-->

currently_reading:
  - { name: "The Open Society and Its Enemies",
      review_link: "https://philosophynow.org/issues/38/The_Open_Society_Revisited" }
  - { name: "Political Liberalism",
      review_link: "http://understandingsociety.blogspot.com/2011/01/rawls-on-political-liberalism.html" }

# About/contact
author:
  name:              James Tranovich
  email:             jtranovich@gmail.com
